export const PLAYLIST_GETINITIALDATA = "PLAYLIST_GETINITIALDATA";
export type PLAYLIST_GETINITIALDATA = typeof PLAYLIST_GETINITIALDATA;

export const PLAYLIST_GETHOT = "PLAYLIST_GETHOT";
export type PLAYLIST_GETHOT = typeof PLAYLIST_GETHOT;

export const SET_STORE = "SET_STORE";
export type SET_STORE = typeof SET_STORE;